workspace:
  base: /go/src
  path: github.com/appleboy/gin-jwt

pipeline:
  vendor:
    image: golang:1.10
    pull: true
    commands:
      - make install

  build:
    image: golang:1.10
    pull: true
    group: testing
    commands:
      - make embedmd-check
      - make vet
      - make fmt-check

  lint:
    image: golang:1.10
    pull: true
    group: testing
    commands:
      - make lint

  coverage:
    image: golang:1.10
    pull: true
    group: testing
    commands:
      - make unit-test-coverage

  generate-coverage:
    image: golang:1.10
    pull: true
    commands:
      - make coverage
    when:
      event: [ push, pull_request ]

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.all
    when:
      event: [ push, pull_request ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
